### PR TITLE
Add support for Ubuntu 16.04 LTS - Xenial Xerus

### PR DESCRIPTION
**Pull request by billinghamj**

### CODE REVIEW

**Comment by billinghamj** [comment]
Also with nothing that vivid has reached EOL - perhaps should be removed

**Comment by billinghamj** [comment]
I have also not been able to run `dante` on my Mac. The Docker stuff doesn't seem to like it.

**Comment by retrohacker** [comment]
Hey @billinghamj! Thank you so much for opening this!

Taking a look now.

Re: `dante`. It is just a puppet master sitting on top of the `docker` cli tool. Are you getting any weird errors out of it?

**Comment by retrohacker** [comment]
I've been merging these changes into the work I was doing with automation stuff. It is on the production build server now. A few of the tests are failing, fixing those now. Should have xenial (and a few other distros) shipped soon!

Thanks for your help here!

**Comment by billinghamj** [comment]
No worries - appreciate it.

I installed the Docker for Mac GUI, but it just seemed to keep crashing. I am using macOS Sierra though so that is quite likely to be the issue.

**Comment by retrohacker** [comment]
This landed in https://github.com/nodesource/docker-node/commit/f708bfe6ab1c88704b8ab7ee0e41f7daca6c7335

**Pull request closed without merging**
